[package]
name = "syllable-rs"
version = "0.1.0"
edition = "2021"
authors = ["cyalen"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8.4"
lazy_static = "1.4.0"
rayon = "1.9.0"
